apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-0
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv-postgresql-0/